import { getAccessToken } from './auth';

export interface DriveFile {
  id: string;
  name: string;
  mimeType: string;
  webViewLink?: string;
  webContentLink?: string;
  size?: string;
  createdTime?: string;
  modifiedTime?: string;
  iconLink?: string;
}

const DRIVE_API_BASE = 'https://www.googleapis.com/drive/v3';
const DRIVE_UPLOAD_BASE = 'https://www.googleapis.com/upload/drive/v3';

// Ensure standard SvaraAI Voiceovers folder exists in Drive
export async function getOrCreateVoiceoverFolder(folderName = 'SvaraAI Voiceovers'): Promise<string> {
  const token = await getAccessToken();
  if (!token) throw new Error('Not authenticated with Google');

  // Search for existing folder
  const query = encodeURIComponent(`name = '${folderName}' and mimeType = 'application/vnd.google-apps.folder' and trashed = false`);
  const searchRes = await fetch(`${DRIVE_API_BASE}/files?q=${query}&fields=files(id, name)`, {
    headers: { Authorization: `Bearer ${token}` }
  });

  if (!searchRes.ok) {
    const err = await searchRes.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to search Google Drive folders');
  }

  const data = await searchRes.json();
  if (data.files && data.files.length > 0) {
    return data.files[0].id;
  }

  // Create folder
  const createRes = await fetch(`${DRIVE_API_BASE}/files`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      name: folderName,
      mimeType: 'application/vnd.google-apps.folder',
      description: 'Directory for audio voiceover files generated by SvaraAI Studio'
    })
  });

  if (!createRes.ok) {
    const err = await createRes.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to create Google Drive folder');
  }

  const folder = await createRes.json();
  return folder.id;
}

// Upload Audio Blob to Google Drive (Multipart upload)
export async function uploadAudioToDrive(
  audioBlob: Blob,
  fileName: string,
  folderId?: string,
  description?: string
): Promise<DriveFile> {
  const token = await getAccessToken();
  if (!token) throw new Error('Not authenticated with Google');

  const metadata: Record<string, any> = {
    name: fileName,
    mimeType: audioBlob.type || 'audio/wav',
    description: description || 'Voiceover generated with SvaraAI Studio'
  };

  if (folderId) {
    metadata.parents = [folderId];
  }

  const boundary = '-------314159265358979323846';
  const delimiter = `\r\n--${boundary}\r\n`;
  const closeDelimiter = `\r\n--${boundary}--`;

  // Read blob as binary array
  const audioBuffer = await audioBlob.arrayBuffer();

  const multipartRequestBody = new Blob([
    delimiter,
    'Content-Type: application/json; charset=UTF-8\r\n\r\n',
    JSON.stringify(metadata),
    delimiter,
    `Content-Type: ${audioBlob.type || 'audio/wav'}\r\n`,
    'Content-Transfer-Encoding: binary\r\n\r\n',
    audioBuffer,
    closeDelimiter
  ]);

  const res = await fetch(`${DRIVE_UPLOAD_BASE}/files?uploadType=multipart&fields=id,name,mimeType,webViewLink,webContentLink,size,createdTime`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': `multipart/related; boundary=${boundary}`
    },
    body: multipartRequestBody
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to upload audio to Google Drive');
  }

  return await res.json();
}

// List user's SvaraAI Voiceover audio files from Google Drive
export async function listDriveVoiceovers(pageSize = 20): Promise<DriveFile[]> {
  const token = await getAccessToken();
  if (!token) throw new Error('Not authenticated with Google');

  const query = encodeURIComponent(`(mimeType contains 'audio/' or name contains '.wav' or name contains '.mp3') and trashed = false`);
  const url = `${DRIVE_API_BASE}/files?q=${query}&pageSize=${pageSize}&orderBy=createdTime desc&fields=files(id,name,mimeType,webViewLink,webContentLink,size,createdTime,modifiedTime,iconLink)`;

  const res = await fetch(url, {
    headers: { Authorization: `Bearer ${token}` }
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to list files from Google Drive');
  }

  const data = await res.json();
  return data.files || [];
}

// Delete file with safety check (Must be confirmed by user in UI)
export async function deleteDriveFile(fileId: string): Promise<void> {
  const token = await getAccessToken();
  if (!token) throw new Error('Not authenticated with Google');

  const res = await fetch(`${DRIVE_API_BASE}/files/${fileId}`, {
    method: 'DELETE',
    headers: { Authorization: `Bearer ${token}` }
  });

  if (!res.ok && res.status !== 204) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to delete file from Google Drive');
  }
}
