import { ScriptPreset } from '../types/tts';

export const SCRIPT_PRESETS: ScriptPreset[] = [
  {
    id: 'ml_doc_intro',
    title: 'കേരള പ്രകൃതി ഡോക്യുമെന്ററി (Documentary)',
    language: 'Malayalam (ml-IN)',
    category: 'malayalam',
    badge: 'മലയാളം Narration',
    suggestedStyle: 'Calm, poetic, deep documentary narrator with natural pauses',
    suggestedVoice: 'Kore',
    text: `ദൈവത്തിന്റെ സ്വന്തം നാടായ കേരളത്തിന്റെ മനോഹാരിത... സഹ്യപർവ്വത നിരകളിൽ നിന്നുത്ഭവിക്കുന്ന കുളിർനദികളും, പച്ചപ്പുനിറഞ്ഞ കായലുകളും, നമ്മുടെ മനസ്സിന് ശാന്തിയും കുളിർമയും പകരുന്നു. പ്രകൃതിയുടെ ഈ വിസ്മയം നമുക്കൊന്നിച്ചു കാണാം.`,
  },
  {
    id: 'ml_youtube_hook',
    title: 'യൂട്യൂബ് / പോഡ്കാസ്റ്റ് ഇൻട്രോ (YouTube Hook)',
    language: 'Malayalam (ml-IN)',
    category: 'malayalam',
    badge: 'Trending Vlog',
    suggestedStyle: 'Energetic, warm, friendly YouTube creator intro',
    suggestedVoice: 'Puck',
    text: `എല്ലാവർക്കും നമസ്കാരം! ഇന്നത്തെ പുതിയ എപ്പിസോഡിലേക്ക് എല്ലാവർക്കും ഹൃദ്യമായ സ്വാഗതം. ഇന്ന് നമ്മൾ ചർച്ച ചെയ്യാൻ പോകുന്നത്, ആർട്ടിഫിഷ്യൽ ഇന്റലിജൻസും നമ്മുടെ ഭാവിയും തമ്മിലുള്ള വിസ്മയകരമായ മാറ്റങ്ങളെക്കുറിച്ചാണ്. വീഡിയോ മുഴുവനായും കാണുക!`,
  },
  {
    id: 'ml_breaking_news',
    title: 'പ്രധാന വാർത്താ ബുള്ളറ്റിൻ (News Anchor)',
    language: 'Malayalam (ml-IN)',
    category: 'malayalam',
    badge: 'News Broadcast',
    suggestedStyle: 'Authoritative, clear, fast-paced Malayalam news anchor',
    suggestedVoice: 'Charon',
    text: `നമസ്കാരം, പ്രധാന വാർത്തകളിലേക്ക് സ്വാഗതം. സാങ്കേതിക വിദ്യാ രംഗത്ത് വിപ്ലവം സൃഷ്ടിച്ച് പുതിയ എഐ മോഡലുകൾ പുറത്തിറങ്ങി. സാധാരണക്കാർക്കും എളുപ്പത്തിൽ ഉപയോഗിക്കാവുന്ന നൂതന സേവനങ്ങളാണ് ഇതിലൂടെ ലഭ്യമാകുന്നത്. കൂടുതൽ വിവരങ്ങൾ ഉടൻ.`,
  },
  {
    id: 'ml_commercial_ad',
    title: 'ബ്രാൻഡ് പ്രൊമോ & പരസ്യം (Commercial Ad)',
    language: 'Malayalam (ml-IN)',
    category: 'malayalam',
    badge: 'Commercial Promo',
    suggestedStyle: 'Persuasive, upbeat, enthusiastic promotional voice',
    suggestedVoice: 'Fenrir',
    text: `നിങ്ങളുടെ സ്വപ്ന ഭവനത്തിനായി ഇതാ ഒരു സുവർണ്ണാവസരം! ഏറ്റവും മികച്ച സൗകര്യങ്ങളും വിശ്വസ്തതയും ഒരുമിക്കുന്ന പ്രീമിയം വില്ലകൾ ഇപ്പോൾ ആകർഷകമായ ഓഫറുകളിൽ സ്വന്തമാക്കാം. ഇന്നുതന്നെ ബുക്ക് ചെയ്യൂ, ജീവിതം ആഘോഷമാക്കൂ!`,
  },
  {
    id: 'ml_story_tale',
    title: 'അമ്മൂമ്മക്കഥ / കുട്ടിക്കഥ (Bedtime Story)',
    language: 'Malayalam (ml-IN)',
    category: 'malayalam',
    badge: 'Audiobook & Story',
    suggestedStyle: 'Gentle, affectionate, bedtime storytelling tone with soft whispers',
    suggestedVoice: 'Aoede',
    text: `ഒരിക്കൽ ഒരു കൊച്ചു ഗ്രാമത്തിൽ, കാടിന്റെ ഓരത്തായി ഒരു കൊച്ചു പൂന്തോട്ടമുണ്ടായിരുന്നു. അവിടെ പാറിനടന്ന ചിത്രശലഭങ്ങൾക്ക് ഒരു രഹസ്യം അറിയാമായിരുന്നു... രാത്രിയാകുമ്പോൾ മിന്നിത്തിളങ്ങുന്ന ആ മാന്ത്രിക പൂവിനെക്കുറിച്ചുള്ള രഹസ്യം!`,
  },
  {
    id: 'en_tech_narration',
    title: 'Global Tech Innovation Voiceover (English)',
    language: 'English (en-US)',
    category: 'multilingual',
    badge: 'Tech & Sci-Fi',
    suggestedStyle: 'Sophisticated, visionary, articulate tech keynote narrator',
    suggestedVoice: 'Zephyr',
    text: `Welcome to the future of speech synthesis. By fusing high-fidelity neural audio with adaptive multilingual intelligence, we empower creators to narrate stories that transcend borders and touch hearts across every language.`,
  },
  {
    id: 'hi_doc_narration',
    title: 'भारतीय संस्कृति व यात्रा (Hindi Narration)',
    language: 'Hindi (hi-IN)',
    category: 'multilingual',
    badge: 'हिन्दी Documentary',
    suggestedStyle: 'Warm, expressive, authentic Hindi narrative voiceover',
    suggestedVoice: 'Kore',
    text: `नमस्ते! भारत की पावन धरती, विविध संस्कृतियों और अनूठी परंपराओं का संगम है। हर राज्य की अपनी मिठास, अपनी जुबां और अपनी कहानी है। आइए, इस अनोखे सफर का हिस्सा बनें।`,
  },
  {
    id: 'ta_promo_narration',
    title: 'தமிழ் விளம்பரம் & அறிமுகம் (Tamil Promo)',
    language: 'Tamil (ta-IN)',
    category: 'multilingual',
    badge: 'தமிழ் Commercial',
    suggestedStyle: 'Crisp, engaging, resonant Tamil promo narrator',
    suggestedVoice: 'Puck',
    text: `அனைவருக்கும் வணக்கம்! உங்கள் வாழ்க்கையை அடுத்த கட்டத்திற்கு கொண்டு செல்ல, புதிய தலைமுறை தொழில்நுட்பம் இப்போது உங்கள் கைகளில். இன்றே தொடங்குங்கள், புதிய உலகை உருவாக்குங்கள்!`,
  },
];

export const VOICE_STYLE_PRESETS = [
  { id: 'natural', label: 'Natural & Warm (സാധാരണ)', desc: 'Clear, comforting tone for general voiceovers' },
  { id: 'documentary', label: 'Documentary (ഡോക്യുമെന്ററി)', desc: 'Deep, contemplative, cinematic storytelling' },
  { id: 'news', label: 'News Anchor (വാർത്താ ബുള്ളറ്റിൻ)', desc: 'Fast, authoritative, broadcast journalism' },
  { id: 'promo', label: 'Promo / Commercial (പരസ്യം)', desc: 'Energetic, punchy, persuasive commercial delivery' },
  { id: 'story', label: 'Audiobook / Story (കഥ പറച്ചിൽ)', desc: 'Expressive with dramatic inflection and soft pacing' },
  { id: 'meditation', label: 'Calm & Meditation (ശാന്തമായ ധ്യാനം)', desc: 'Whispery, serene, slow tempo for mindfulness' },
];
